# Generated by Django 5.2.5 on 2025-09-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('method', models.CharField(default='GET', max_length=8)),
                ('expected_code', models.PositiveSmallIntegerField(default=200)),
                ('timeout_s', models.PositiveSmallIntegerField(default=10)),
                ('interval_s', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='core.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=8)),
                ('latency_ms', models.PositiveIntegerField()),
                ('code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['monitor', '-ts'], name='monitors_ch_monitor_84d60d_idx')],
            },
        ),
    ]
