# Generated by Django 5.2.5 on 2026-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="description",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
